### PR TITLE
Add Customise App

### PR DESCRIPTION
**Pull request by tomlister**
Customise needs an icon, maybe a paint brush [gif from geocities](https://gifcities.org/)?
This is barebones for now, and I plan to add custom images and solid colors.

### CODE REVIEW

**Comment by Marak** [comment]
@tomlister -

Thank you for your contribution!

`Customize` isn't a great name for this, we'd rather keep the `App` named `Wallpaper` and use that.

The concept is that `desktop.wallpaper` is responsible for managing wallpaper settings.

If you can modify your PR to use the existing `desktop.wallpaper` we can get this merged.

It would also be good if we had at least one more options for wallpaper.

To start we could have:
  - Matrix Wallpaper with color settings
  - Static CSS `background-color` setting

Each wallpaper logic can be hard-coded directly into `desktop.wallpaper.js` for now. If you can rig up the UX portion we can make sure the local storage saves the setting later.

Cheers!

**Comment by tomlister** [comment]
Want me to address issue #19  ?

**Comment by tomlister** [comment]
Alright, resolved. Sorry, if the implementation is scuffed. I'm running on one coffee and 4 hours sleep.

**Comment by Marak** [comment]
Thanks again for your contributions.

Merged.

Will deploy after a few more minor updates.

**Pull request merged**
